import sqlite3
import os
from datetime import datetime

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tubescribe_library.db")


def get_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    return conn


def init_db():
    conn = get_connection()
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS videos (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            video_id TEXT UNIQUE,
            url TEXT,
            title TEXT,
            channel TEXT,
            channel_url TEXT,
            description TEXT,
            duration TEXT,
            view_count INTEGER,
            upload_date TEXT,
            thumbnail TEXT,
            transcript TEXT,
            speakers TEXT,
            analysis TEXT,
            detail_level TEXT,
            key_quotes TEXT,
            processed_at TEXT DEFAULT CURRENT_TIMESTAMP
        );

        CREATE VIRTUAL TABLE IF NOT EXISTS videos_fts USING fts5(
            title, channel, transcript, analysis, speakers,
            content='videos',
            content_rowid='id'
        );

        -- Triggers to keep FTS index in sync
        CREATE TRIGGER IF NOT EXISTS videos_ai AFTER INSERT ON videos BEGIN
            INSERT INTO videos_fts(rowid, title, channel, transcript, analysis, speakers)
            VALUES (new.id, new.title, new.channel, new.transcript, new.analysis, new.speakers);
        END;

        CREATE TRIGGER IF NOT EXISTS videos_ad AFTER DELETE ON videos BEGIN
            INSERT INTO videos_fts(videos_fts, rowid, title, channel, transcript, analysis, speakers)
            VALUES ('delete', old.id, old.title, old.channel, old.transcript, old.analysis, old.speakers);
        END;

        CREATE TRIGGER IF NOT EXISTS videos_au AFTER UPDATE ON videos BEGIN
            INSERT INTO videos_fts(videos_fts, rowid, title, channel, transcript, analysis, speakers)
            VALUES ('delete', old.id, old.title, old.channel, old.transcript, old.analysis, old.speakers);
            INSERT INTO videos_fts(rowid, title, channel, transcript, analysis, speakers)
            VALUES (new.id, new.title, new.channel, new.transcript, new.analysis, new.speakers);
        END;

        -- Tags (auto-generated by LLM)
        CREATE TABLE IF NOT EXISTS video_tags (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            video_id TEXT NOT NULL,
            tag TEXT NOT NULL,
            UNIQUE(video_id, tag),
            FOREIGN KEY (video_id) REFERENCES videos(video_id) ON DELETE CASCADE
        );

        -- Collections (user-created groups)
        CREATE TABLE IF NOT EXISTS collections (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        );

        -- Many-to-many: videos in collections
        CREATE TABLE IF NOT EXISTS collection_videos (
            collection_id INTEGER NOT NULL,
            video_id TEXT NOT NULL,
            PRIMARY KEY (collection_id, video_id),
            FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE CASCADE,
            FOREIGN KEY (video_id) REFERENCES videos(video_id) ON DELETE CASCADE
        );
    """)
    conn.execute("PRAGMA foreign_keys = ON")
    # Migration: add key_quotes column if missing
    cols = [row[1] for row in conn.execute("PRAGMA table_info(videos)").fetchall()]
    if "key_quotes" not in cols:
        conn.execute("ALTER TABLE videos ADD COLUMN key_quotes TEXT")
        conn.commit()
    conn.close()


def save_video(video_id, url, metadata, transcript, speakers, analysis, detail_level, key_quotes=None):
    conn = get_connection()
    conn.execute("""
        INSERT INTO videos (video_id, url, title, channel, channel_url, description,
                            duration, view_count, upload_date, thumbnail,
                            transcript, speakers, analysis, detail_level, key_quotes, processed_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(video_id) DO UPDATE SET
            transcript=excluded.transcript,
            speakers=excluded.speakers,
            analysis=excluded.analysis,
            detail_level=excluded.detail_level,
            key_quotes=COALESCE(excluded.key_quotes, videos.key_quotes),
            processed_at=excluded.processed_at
    """, (
        video_id,
        url,
        metadata.get("title", ""),
        metadata.get("channel", ""),
        metadata.get("channel_url", ""),
        metadata.get("description", ""),
        metadata.get("duration", ""),
        metadata.get("view_count"),
        metadata.get("upload_date", ""),
        metadata.get("thumbnail", ""),
        transcript,
        speakers,
        analysis,
        detail_level,
        key_quotes,
        datetime.now().isoformat(),
    ))
    conn.commit()
    conn.close()


def search_videos(query):
    conn = get_connection()
    rows = conn.execute("""
        SELECT v.*, snippet(videos_fts, 0, '<b>', '</b>', '...', 30) AS title_snippet,
               snippet(videos_fts, 2, '<b>', '</b>', '...', 30) AS transcript_snippet
        FROM videos_fts
        JOIN videos v ON v.id = videos_fts.rowid
        WHERE videos_fts MATCH ?
        ORDER BY rank
        LIMIT 20
    """, (query,)).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def list_all_videos():
    conn = get_connection()
    rows = conn.execute("""
        SELECT id, video_id, url, title, channel, duration, detail_level, processed_at
        FROM videos
        ORDER BY processed_at DESC
    """).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_video(video_id):
    conn = get_connection()
    row = conn.execute("SELECT * FROM videos WHERE video_id = ?", (video_id,)).fetchone()
    conn.close()
    return dict(row) if row else None


def delete_video(video_id):
    conn = get_connection()
    conn.execute("DELETE FROM videos WHERE video_id = ?", (video_id,))
    conn.commit()
    conn.close()


def count_videos():
    conn = get_connection()
    count = conn.execute("SELECT COUNT(*) FROM videos").fetchone()[0]
    conn.close()
    return count


# --- Key Quotes ---

def save_key_quotes(video_id, quotes_markdown):
    conn = get_connection()
    conn.execute("UPDATE videos SET key_quotes = ? WHERE video_id = ?", (quotes_markdown, video_id))
    conn.commit()
    conn.close()


def get_key_quotes(video_id):
    conn = get_connection()
    row = conn.execute("SELECT key_quotes FROM videos WHERE video_id = ?", (video_id,)).fetchone()
    conn.close()
    return row["key_quotes"] if row and row["key_quotes"] else None


# --- Tags ---

def save_tags(video_id, tags):
    conn = get_connection()
    for tag in tags:
        tag = tag.strip().lower()
        if tag:
            conn.execute(
                "INSERT OR IGNORE INTO video_tags (video_id, tag) VALUES (?, ?)",
                (video_id, tag),
            )
    conn.commit()
    conn.close()


def get_tags(video_id):
    conn = get_connection()
    rows = conn.execute(
        "SELECT tag FROM video_tags WHERE video_id = ? ORDER BY tag", (video_id,)
    ).fetchall()
    conn.close()
    return [r["tag"] for r in rows]


def get_all_tags():
    conn = get_connection()
    rows = conn.execute("""
        SELECT tag, COUNT(*) as count
        FROM video_tags
        GROUP BY tag
        ORDER BY count DESC, tag
    """).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_videos_by_tag(tag):
    conn = get_connection()
    rows = conn.execute("""
        SELECT v.id, v.video_id, v.url, v.title, v.channel, v.duration, v.detail_level, v.processed_at
        FROM videos v
        JOIN video_tags vt ON v.video_id = vt.video_id
        WHERE vt.tag = ?
        ORDER BY v.processed_at DESC
    """, (tag,)).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# --- Collections ---

def create_collection(name):
    conn = get_connection()
    cursor = conn.execute("INSERT OR IGNORE INTO collections (name) VALUES (?)", (name.strip(),))
    conn.commit()
    cid = cursor.lastrowid
    if not cid:
        row = conn.execute("SELECT id FROM collections WHERE name = ?", (name.strip(),)).fetchone()
        cid = row["id"] if row else None
    conn.close()
    return cid


def delete_collection(collection_id):
    conn = get_connection()
    conn.execute("DELETE FROM collection_videos WHERE collection_id = ?", (collection_id,))
    conn.execute("DELETE FROM collections WHERE id = ?", (collection_id,))
    conn.commit()
    conn.close()


def add_to_collection(collection_id, video_id):
    conn = get_connection()
    conn.execute(
        "INSERT OR IGNORE INTO collection_videos (collection_id, video_id) VALUES (?, ?)",
        (collection_id, video_id),
    )
    conn.commit()
    conn.close()


def remove_from_collection(collection_id, video_id):
    conn = get_connection()
    conn.execute(
        "DELETE FROM collection_videos WHERE collection_id = ? AND video_id = ?",
        (collection_id, video_id),
    )
    conn.commit()
    conn.close()


def list_collections():
    conn = get_connection()
    rows = conn.execute("""
        SELECT c.id, c.name, COUNT(cv.video_id) as video_count
        FROM collections c
        LEFT JOIN collection_videos cv ON c.id = cv.collection_id
        GROUP BY c.id
        ORDER BY c.name
    """).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_collection_videos(collection_id):
    conn = get_connection()
    rows = conn.execute("""
        SELECT v.id, v.video_id, v.url, v.title, v.channel, v.duration, v.detail_level, v.processed_at
        FROM videos v
        JOIN collection_videos cv ON v.video_id = cv.video_id
        WHERE cv.collection_id = ?
        ORDER BY v.processed_at DESC
    """, (collection_id,)).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_video_collections(video_id):
    conn = get_connection()
    rows = conn.execute("""
        SELECT c.id, c.name
        FROM collections c
        JOIN collection_videos cv ON c.id = cv.collection_id
        WHERE cv.video_id = ?
        ORDER BY c.name
    """, (video_id,)).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# Initialize on import
init_db()
